name: Mercury wheels Build and Publish cibuildwheels

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-mercury-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment:
      name: pypi
      url: https://pypi.org/p/mercury-python-test
    permissions:
      id-token: write
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          detch-depth: 1
          submodules: 'true'

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libssl-dev make

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Install pip packages
        run: python -m pip install cython cibuildwheel==2.20.0

      - name: Build Mercury
        run: cd mercury/ && ./configure && make

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        env:
          CIBW_ARCHS_LINUX: x86_64 #aarch64 TODO add ARM instances
          CIBW_ENVIRONMENT: CC='g++' CXX='g++'
          CIBW_SKIP: "*-musllinux_* pp* cp1*" # TODO remove cp1*
          CIBW_BEFORE_ALL: yum install -y openssl-devel make zlib-devel || apt-get install -y zlib1g-dev libssl-dev make || apk add zlib1g-dev libssl-dev make

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse/
